
--only if local
DROP DATABASE IF EXISTS bbq_db;
CREATE DATABASE bbq_db;
USE bbq_db;
--

CREATE TABLE bbq(
    id INT PRIMARY KEY AUTO_INCREMENT,
    location VARCHAR(45) NOT NULL,
    smoked BIT DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);